Preliminary 2-hour "port" of shmem-conduit to IRIX (SGI Origin 2000). This "port" includes only 1 new line of executable C code and 2 additional prototypes for system-provided functions.  The remainder of this commit is either configure logic, comments, or changes to the #if's to replace most instances of PLATFORM_ARCH_ALTIX with defined(SGI_SHMEM).
To compile this "port" requires an explict --enable-irix-shmem at configure
time because preliminary testing shows the following failures:

Test results: 5 failures

 *-* shmem-conduit/SEQ-FAST-debug/testenv GASNet is \"Global Address Space Networking\" *-*

ERROR: node 1/2 argc == 7, expected 4 (at /usr/people/paulhhargrove/upc_runtime/gasnet/tests/testenv.c:71)
ERROR: node 0/2 argc == 7, expected 4 (at /usr/people/paulhhargrove/upc_runtime/gasnet/tests/testenv.c:71)


 *-* shmem-conduit/SEQ-FAST-debug/testcore2  *-*

ERROR calling: gasnet_attach(htable, sizeof(htable)/sizeof(gasnet_handlerentry_t), TEST_SEGSZ_REQUEST, TEST_MINHEAPOFFSET)
ERROR calling: gasnet_attach(htable, sizeof(htable)/sizeof(gasnet_handlerentry_t), TEST_SEGSZ_REQUEST, TEST_MINHEAPOFFSET)

 *-* shmem-conduit/SEQ-FAST-debug/testvis  *-*

*** Caught a fatal signal: SIGBUS(10) on node 0/2
*** Caught a fatal signal: SIGBUS(10) on node 1/2
ERROR: Test exited with failure code=1

 *-* shmem-conduit/SEQ-FAST-debug/testcoll  *-*

*** Caught a fatal signal: SIGBUS(10) on node 1/2
ERROR: Test exited with failure code=1

 *-* shmem-conduit/SEQ-FAST-debug/testvisperf -maxdata 131072 -maxcontig 512 10 *-*

*** Caught a fatal signal: SIGBUS(10) on node 0/2
ERROR: Test exited with failure code=1